# Generated by Django 4.2.3 on 2023-07-16 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Zaid', max_length=255, null=True, verbose_name='Customer_name')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='customer_address')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='customer_phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='customer_email')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='product_name')),
                ('section', models.CharField(choices=[('Book_Store', 'Book_Store'), ('Draw_Store', 'Draw_Store')], max_length=100, verbose_name='section')),
                ('price', models.FloatField(default=0.0, verbose_name='product_price')),
                ('image', models.URLField(blank=True, null=True, verbose_name='product_image')),
                ('category', models.CharField(blank=True, choices=[('Scientific', 'Scientific'), ('Art', 'Art'), ('Historic', 'Historic'), ('Novels', 'Novels'), ('Fictional', 'Fictional')], max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_rare', models.BooleanField(default=False, verbose_name='is_rare')),
                ('is_DrawTool', models.BooleanField(default=False, verbose_name='is_book')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('details', models.CharField(blank=True, max_length=255, null=True, verbose_name='Details')),
                ('date', models.DateField(verbose_name='order date')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
    ]
